version: '2'

services:
  bundler:
    container_name:   bundler
    ports: [ '3000:3000' ]
    image: skypigr/bundler:0.2.3
    restart: on-failure

    volumes:
      - ./workdir:/app/workdir:ro

    environment:
      url: https://${HOST}/
      LETSENCRYPT_HOST: $HOST
      LETSENCRYPT_PORT: 3000
      VIRTUAL_HOST: $HOST
      VIRTUAL_PATH: /
      VIRTUAL_DEST: /
    mem_limit: 300M
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "10"
